name: "tagged-release"

on: push

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest build"
          files: |
            *.zip
