name: "tagged-release"

on: push
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install
        working-directory: ${{ github.workspace }}

      - name: Run semantice release
        run: |
          npx semantic-release
        working-directory: ${{ github.workspace }}
        
      - name: Print package.json version (before)
        run: |
          echo "package.json version (before): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}

      - name: Fetch Latest Commit
        run: |
          git fetch
          git reset --hard origin/main
      - name: Print package.json version (after)
        run: |
          echo "package.json version (after): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ./dist/*.zip
